name: Enrich Data
on:
  push:
    branches:
      - 'cms/**'

jobs:
  update-size:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Enrich Data
        run: yarn data:enrich

      - name: Modernize Russian
        run: yarn data:modernize-russian

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-update data size [skip ci]'
          file_pattern: '.'
          commit_user_name: 'GitHub Action'
          commit_user_email: 'action@github.com'
          skip_dirty_check: false
          skip_fetch: true
